### ISSUE TITLE
Accept self-signed SSL certs

### ISSUE THREAD

**Issue by mjturt** [City-of-Helsinki/profile-gdpr-api-tester#2]
Currently, connection is dropped when invalid (self-signed) SSL certificate used on backend. Our project's (YJDH Helsinki-lisä) dev environments are using HTTPS, even locally. I would suggest adding a configuration parameter to control whether the SSL certificate is verified. This would allow the use of this tool in local environments in cases like ours.

I got this working for myself by passing `verify_ssl=False` parameter to `session`. E.g.:

```python
response = await getattr(session, method)(url, params=params, verify_ssl=False)
```

In `main.py` on the line 248.

Nice work btw :+1: The tool helps a lot!

**Comment by mikkokeskinen** [comment]
Good catch! Thanks for reporting. The SSL checks should be relaxed now.
